### ISSUE TITLE
 No such file or directory: 'amplitude/import/265511_2020-11-17_22#41.json'

### ISSUE THREAD

**Issue by stefdelec** [MartijnSch/amplitude-bigquery#2]
```
Traceback (most recent call last):
  File "amplitude-bigquery.py", line 186, in <module>
    import_events_file = open("amplitude/import/" + file_json(file), "w+")
IOError: [Errno 2] No such file or directory: 'amplitude/import/265511_2020-11-17_22#41.json'


```

Thanks for the script. I created bucket + tables. But I stay stuck to this line of code. I have tried to understand where 'amplitude/import/'  directory is created but I can't find when. Am I missing something?

**Comment by MartijnSch** [comment]
@stefdelec You're not missing anything, you have to manually create the folder as the script actually doesn't take care of that. I might add that into the script at some point, it's honestly an oversight from my initial build.

**Comment by stefdelec** [comment]
Ok I got it!

**Comment by MartijnSch** [comment]
Glad you figured it out, I noticed your edits too. Let me know if you have more questions!
