### ISSUE TITLE
missing one hour in the day

### ISSUE THREAD

**Issue by stefdelec** [MartijnSch/amplitude-bigquery#3]
You wrote 01 to 23 and it should be 00 to 23 
You are missing one hour.

**IMPORTANT NOTE: If you wish to export a whole day, then it would be from T00 to T23. The maximum time range you can query at once is 365 days.**
https://help.amplitude.com/hc/en-us/articles/205406637-Export-API-Export-Your-Project-s-Event-Data

**Comment by MartijnSch** [comment]
Great catch, fixed this!
